name: run tests

on:
  push:
    paths:
      - services/posts/**
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./services/posts

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
